name: Go Docker CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Run Tests
        run: go test ./...

  docker:
    name: Build and Push Docker Image
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-app:${{ github.ref_name }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/go-app:${{ github.ref_name }} ${{ secrets.DOCKER_USERNAME }}/go-app:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/go-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/go-app:latest
